README.md, iclient.sh
=> Update build instructions, iclient script to find Settings

Cargo.toml, client/Cargo.toml, client/src/ecdsa/keygen.rs, client/src/state_entity/api.rs, client/src/state_entity/deposit.rs, client/src/state_entity/transfer.rs, client/src/state_entity/util.rs, client/src/wallet/shared_key.rs, client/src/wallet/wallet.rs, integration-tests/.gitignore, integration-tests/README.md, integration-tests/src/test.rs, server/.gitignore, server/Cargo.toml, server/README.md, server/Settings.toml, server/src/error.rs, server/src/lib.rs, server/src/routes/ecdsa.rs, server/src/routes/state_entity.rs, server/src/server.rs, server/src/state_chain.rs, server/src/storage/db.rs, server/src/storage/mod.rs, server/src/tests.rs, shared/src/structs.rs
https://github.com/commerceblock/mercury/issues/6 - Sparse Merkle Tree integration
https://github.com/commerceblock/mercury/issues/5 - Wallet verification
=> Smt integration 

integration-tests/src/batch_transfer_test.rs, integration-tests/src/lib.rs, integration-tests/src/simulation.rs, integration-tests/src/test.rs, server/src/config.rs, server/src/error.rs, server/src/lib.rs, server/src/main.rs, server/src/protocol/deposit.rs, server/src/protocol/transfer.rs, server/src/protocol/transfer_batch.rs, server/src/protocol/util.rs, server/src/protocol/withdraw.rs, server/src/server.rs, server/src/storage/db.rs, server/src/storage/mod.rs, shared/src/mainstay.rs
=> Set db connection from rocket config. Return error on failure to get a connection from the pool.

Dockerfile, client/src/utilities/requests.rs
- mainstay cert error
- small delay between http requests
=> Develop - fix prod issues

client/src/utilities/requests.rs, server/src/server.rs
- Add sleep timer to Clients GET request
- Fix bug in which smt db is not set to testing location
- Add test/reset-db to server routes
=> Missed changes from previous commit

client/Cargo.toml, client/README.md, client/Settings.toml, client/src/error.rs, client/src/lib.rs, client/src/main.rs, client/src/state_entity/api.rs, client/src/wallet/wallet.rs, integration-tests/src/lib.rs, integration-tests/src/simulation.rs, shared/Cargo.toml, shared/src/lib.rs
=> Optionally connect client via Tor

client/src/lib.rs, server/src/protocol/conductor.rs
* Some stats for speed of get_new_tor_id
* Test and correct get_new_tor_id - client connection refreshed after tor sent NEWNYM signal to use the new tor id
=> Correct tor

server/src/protocol/conductor.rs, server/src/server.rs, shared/src/blinded_token.rs, shared/src/lib.rs, shared/src/mocks/mock_electrum.rs, shared/src/structs.rs
BLinded signature implementation and inclusion in Conductor
=> Blinded sigs

Cargo.toml, client/Cargo.toml, server/Cargo.toml, shared/Cargo.toml
Edited all Cargo.toml to pull from a specific tag for dependencies that are github repos
=> Set forked git repo deps to pull from tags

server/Cargo.toml, server/src/watch.rs, shared/Cargo.toml
Fix link error caused by out of date dependency
=> Watchblock dev

client/cli.yml, client/src/error.rs, client/src/lib.rs, client/src/main.rs, client/src/state_entity/conductor.rs, client/src/state_entity/mod.rs, client/src/state_entity/transfer.rs, client/src/wallet/shared_key.rs, client/src/wallet/wallet.rs, integration-tests/src/batch_transfer_test.rs, integration-tests/src/lib.rs, server/src/error.rs, server/src/lib.rs, server/src/protocol/conductor.rs, server/src/protocol/transfer.rs, server/src/protocol/util.rs, server/src/server.rs, server/src/storage/db.rs, server/src/storage/monotree.rs, shared/src/blinded_token.rs, shared/src/error.rs, shared/src/lib.rs, shared/src/state_chain.rs, shared/src/structs.rs, shared/src/swap_data.rs
=> Client conductor blinded

server/Cargo.toml, server/src/protocol/conductor.rs, server/src/protocol/deposit.rs, server/src/protocol/transfer.rs, server/src/protocol/withdraw.rs, server/src/server.rs
Prometheus rocket faring (all route counters) and timing histograms and custom counters for deposits, withdrawals, transfers and swap registrations. 
Prometheus metrics available on `/metrics`
=> Prometheus metrics

server/src/protocol/ecdsa.rs, server/src/protocol/transfer_batch.rs
Each keygen function posts the wallet message to the lockbox endpoints
Prints the response and timing to logs.
=> Keygen dummy calls

client/Cargo.toml, server/Cargo.toml
Remove schnorr and eddsa dependencies
=> remove unused dependencies

server/src/protocol/ecdsa.rs
Fix for lockbox keygen/first return data
=> keygen first return id

client/cli.yml, client/src/daemon.rs, client/src/main.rs, client/src/state_entity/api.rs, integration-tests/src/test.rs, server/src/lib.rs, server/src/protocol/conductor.rs, server/src/protocol/util.rs, server/src/server.rs, server/src/storage/db.rs, server/src/storage/monotree.rs, shared/Cargo.toml, shared/src/structs.rs
Map of amount|size : registrations for registered UTXOs from /swaps/groupinfo
Map of amount : frequency for deposited statecoins from /info/coinsinfo
=> swap group status and coins histogram

client/Cargo.toml, client/src/utilities/encoding.rs, shared/src/structs.rs
New custom message serialization scheme, compatible with mercury wallet.
=> Transfer message encoding

client/src/state_entity/transfer.rs, integration-tests/src/lib.rs, server/Cargo.toml, server/Settings.toml, server/src/config.rs, server/src/lib.rs, server/src/protocol/conductor.rs, server/src/protocol/transfer.rs, server/src/protocol/transfer_batch.rs, server/src/protocol/util.rs, server/src/server.rs, server/src/storage/db.rs, server/src/storage/monotree.rs
New API to get stored transfer messages querying by receive seaddr/proof_key.
=> Get transfer message by key

server/src/error.rs, server/src/protocol/requests.rs
=> chore: add better lockbox errorhandling

server/Cargo.toml, server/src/lib.rs
=> Remove unused deps

Cargo.lock, server/src/config.rs, server/src/protocol/deposit.rs, server/src/protocol/ecdsa.rs, server/src/protocol/util.rs
=> Optional pow

Cargo.lock, server/src/error.rs, server/src/protocol/util.rs
* Add missing rate limiter check.
* Change rate limiter error messages.
=> Rate limiter fix

Cargo.lock, client/src/daemon.rs, client/src/state_entity/withdraw.rs, integration-tests/src/batch_transfer_test.rs, integration-tests/src/lib.rs, integration-tests/src/test.rs, server/src/protocol/ecdsa.rs, server/src/protocol/transfer.rs, server/src/protocol/withdraw.rs, server/src/server.rs, shared/src/util.rs
- Return witness from ecdsa/sign/second for withdrawal.
- Block transfer_sender if statechain is in withdrawal.
=> Withdraw rbf

server/src/config.rs, server/src/protocol/conductor.rs, server/src/protocol/util.rs, shared/src/structs.rs, shared/src/swap_data.rs
Wallet version and message in fee info object
Minimum wallet version set for swap registration
=> Wallet version info

server/src/protocol/deposit.rs
Don't create a new statechain entry on each call of deposit_confirm if one already exists (in case of wallet driven RBF on deposit).
=> Update statechain on rbf

client/src/state_entity/withdraw.rs, integration-tests/src/lib.rs, integration-tests/src/test.rs, server/src/lib.rs, server/src/protocol/util.rs, server/src/protocol/withdraw.rs, shared/src/structs.rs
Return receiver address of withdrawing statecoins with recovery data.
=> Return receiver address of withdrawing statecoins with recovery data.

Cargo.lock, shared/Cargo.toml
Reverts commerceblock/mercury#368
=> Revert "Bump libsecp256k1 from 0.3.5 to 0.5.0"

Cargo.lock, shared/src/util.rs
=> Test tx_withdraw_build

doc/tutorial.md
This PR adds a tutorial on how to configure the server, the daemon, and how to use the CLI to interact with them.
=> Add tutorial about server / client usage

client/src/ecdsa/keygen.rs, client/src/lib.rs, client/src/state_entity/api.rs, client/src/state_entity/deposit.rs, client/src/state_entity/transfer.rs, client/src/state_entity/withdraw.rs, client/src/utilities/requests.rs, client/src/wallet/shared_key.rs, client/src/wallet/wallet.rs, server/Settings.toml, server/src/config.rs, server/src/error.rs, server/src/lib.rs, server/src/protocol/deposit.rs, server/src/protocol/ecdsa.rs, server/src/protocol/mod.rs, server/src/protocol/pay_on_deposit.rs, server/src/protocol/requests.rs, server/src/protocol/util.rs, server/src/server.rs, server/src/storage/db.rs, server/src/storage/monotree.rs, shared/src/structs.rs, shared/src/util.rs
Pay for deposit addresses via LN invoice or tokens.
=> Pay on deposit
