commerceblock/mercury

integration-tests/Cargo.toml
integration-tests/src/batch_transfer_test.rs
integration-tests/src/lib.rs
integration-tests/src/test.rs
server/Cargo.toml
server/src/lib.rs
server/src/storage/db.rs
server/src/tests.rs

The serial_test crate is used to serialise tests as needed.
Tests that need to be run in series are annotated with #[serial].

Run tests in series as needed

---

server/Rocket.toml
server/src/config.rs
server/src/server.rs

I believe this keep_alive parameter is the cause of the issues we are having with current prod version.

allow ROcket config to be set via env vars. Default keep alive to 100

---

server/src/error.rs
server/src/protocol/ecdsa.rs
server/src/protocol/mod.rs
server/src/protocol/requests.rs
server/src/protocol/transfer.rs
server/src/server.rs
shared/src/structs.rs

Interface:
ECDSA: 
first_message: KeyGenMsg1 -> party_one::KeyGenFirstMsg (user_id auth by server)
second_message: KeyGenMsg2 -> party1::KeyGenParty1Message2
sign_first: SignMsg1 -> party_one::EphKeyGenFirstMsg (user_id auth by server)
sign_second: SignMsg2 -> Vec<Vec<u8>> (lockbox return witness only: sighash checks, tx sig add and storage by server). 
Transfer:
x1 generated by server (transfer_sender). 
transfer_receiver: KUSendMsg -> KUReceiveMsg (lockbox receives [user_id, shared_key_id, x1, t1, o2_pub] and returns theta and s2_pub after creating a new s2 - but not deleting the old one yet in case of batch failure). 
transfer_finalize: KUFinalize -> KUAttest (lockbox receives [user_id, shared_key_id] and then deletes the old s2, and returns a deletion attestation).

Lockbox interface

---

client/src/state_entity/transfer.rs
server/Cargo.toml
server/src/lib.rs
server/src/protocol/ecdsa.rs
server/src/protocol/transfer.rs
server/src/server.rs
server/src/storage/db.rs
server/src/storage/monotree.rs
shared/src/structs.rs

t2 is encrypted by client in TransferMsg4 with the SE public key share, and decrypted by the SE. 
SE public key share (`s1pubkey`) saved to UserSession DB during keygen. 
`s1pubkey` retrieved from SE by client in `transfer_receiver` (new route/API).

t2 encryption/decryption

---

server/Settings.toml
server/src/config.rs
server/src/protocol/deposit.rs
server/src/protocol/transfer.rs
server/src/protocol/util.rs
shared/src/mocks/mock_electrum.rs

`verify_tx_confirmed` now just checks that the deposit tx is confirmed within `required_confirmation` which is set in the config. If not, it returns error with details : "Funding Transaction not found.", "Funding Transaction not confirmed.", "Funding Transaction insufficient confirmations."
`verify_tx_confirmed` also called when starting a `transfer_sender`
`block_time` removed from the config.

confirmation checks

---

server/src/protocol/requests.rs
server/src/protocol/transfer.rs

New connection for each lockbox call. 
Valid dummy S2 value when lockbox active.

lockbox client and s2 fix

---

integration-tests/src/test.rs
server/Settings.toml
server/src/protocol/transfer.rs
server/src/protocol/util.rs
server/src/storage/db.rs

Transfer sender can be re-run before finalize to enable swaps failure rollback/recovery. Transfer table is updated. 
Backup tx is saved to DB after each signing (prepare_sign) to decrement the locktime correctly. 
New transfer re-send integration test.

Enable transfer rollback

---

server/src/config.rs
server/src/protocol/conductor.rs

Set the swap group timeout in seconds with config variable "group_timeout". After this amount of time after a swap group has been formed, the ongoing swap information will be removed from the scheduler memory.

Swap timeout

---

server/Settings.toml
server/src/config.rs
server/src/protocol/conductor.rs
server/src/server.rs
shared/src/structs.rs

When a swap group (of any size or amount) reaches 2 registrations, a countdown timer is started ( set to config.init_timeout ). When the timeout is reached, the swap executes irrespective of the total registrations (> 1). 
If the group max number is reached before the countdown expires, then the swap executes immediately as before.

Swap group countdown

---

server/src/protocol/deposit.rs
server/src/protocol/ecdsa.rs
server/src/protocol/util.rs

* Rate limit for deposit init
* Include the key in the rate limit error message
* check_auth in ecdsa second_message

Rate limit deposit_init. Include key in rate limit error.

---

Cargo.lock
server/src/protocol/conductor.rs
server/src/protocol/transfer.rs
server/src/protocol/transfer_batch.rs
server/src/protocol/util.rs
server/src/protocol/withdraw.rs
server/src/storage/db.rs
shared/src/state_chain.rs

Simplify enforcement of non-zero StateChain length in the following way:
- Create a new struct with the same data structure as StateChain called StateChainUnchecked that can deserialise.
- Check StateChain length is non-zero on instantiation or conversion from StateChainUnchecked. 
- Do not enable deserilisation for StateChain. 
- Make the data in StateChain and StateChainUnchecked private.

Force non-zero StateChain length

---

client/Settings.toml
server/src/protocol/util.rs

If a new deposit backup tx is signed, the locktime must be the same as previous txs.

Deposit tx replica check

---

Cargo.lock
client/src/daemon.rs
client/src/state_entity/conductor.rs
client/src/state_entity/transfer.rs
integration-tests/src/batch_transfer_test.rs
integration-tests/src/lib.rs
integration-tests/src/test.rs
server/src/lib.rs
server/src/protocol/transfer.rs
server/src/storage/db.rs
server/src/storage/monotree.rs
shared/src/structs.rs

If batch transfer, batch id is supplied to transfer sender and stored in the transfer table. 
On transfer receiver, the batch ID is checked.

Batch id for transfer sender

---

Cargo.lock
server/src/protocol/deposit.rs
server/src/protocol/transfer.rs
server/src/protocol/util.rs
server/src/server.rs
shared/src/structs.rs

- Check lockbox response on keyupdate/second
- Do lockbox keyupdate/second before DB state update in transfer finalise (so can be run again if error). 
- New API call for completing keyupdate/second for any existing coins in error state.

features for preventing and recovering from key update failure

---

README.md

This PR adds build instructions for Fedora 35 and Ubuntu 20.04 / 21.10 and a note warning about the required OpenSSL version (1.1.1 not 3.0.x).

Update README.md with building instructions

---

rust-toolchain.toml

Add `rust-toolchain.toml` with the expected nightly version (`nightly-2021-07-16`).
With this file, the project can be built right after cloning, without manually configuring the toolchain.
This also documents the right toolchain version.

Add rust-toolchain with the expected nightly version

---

server/src/protocol/ecdsa.rs
server/src/storage/db.rs

The column in table ECDSA is created with the name `keygensecondmessage` while the enum has the name `KeyGenSecondMsg`.
This causes an error because the column does not exist.
Also, the `db.set_keygen_second_msg` command is not propagating the error, so `?` has been added.
And it has been moved to the end of the function, so the same command can be used both for lockbox and server.

Fix column name and error propagation

---

client/src/utilities/requests.rs

This PR increases the GET/POST request timeout so that the client can complete the swap operation.
The JS wallet also seems to use a high timeout.
https://github.com/layer2tech/mercury-wallet/blob/d96df82c51223466260407c22865452867267f7a/src/wallet/http_client.ts#L7

Increase request timeout

---

client/src/state_entity/transfer.rs

The `swap/second` returns a SCEAddress with null `tx_backup_addr` and `transfer_sender` function uses this to replace the previous owner. 
If the `tx_backup_addr` is null, the previous owner persists and then the error `Backup Tx Receiving Address not found in this wallet` occurs in the swap process.
Using `proof_key` to set the new owner in the backup transaction fixes this.

Instead of using `tx_backup_addr`, use `proof_key` to set the new owner

---

client/src/state_entity/conductor.rs

Currently the `do_swap` function manually generates the SE address for the swap but does not add it to `se_backup_keys` nor assign a `tx_backup_addr` to it.
Apparently there is no need to re-implement the SE address generation logic as there is a `get_new_state_entity_address` function that already does that.
This PR aims to fix the bug `thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Generic("Backup Tx receiving address not found in this wallet!")', client/src/daemon.rs:302:26` which happens in swap process, but the error persists even after this patch.
Even so, for the reasons mentioned above, I still think it's worth the fix proposed by PR or at least a discussion about how the SE address is being generated in the swap process.

Change swap to use `get_new_state_entity_address` function
